/* oxlint-disable react/set-state-in-effect -- legacy component retained only for migration history; not imported by the app. */
import { useCallback, useEffect, useState } from 'react'
import { Link, NavLink, Navigate, useParams } from 'react-router'
import { useAuth } from '../auth/AuthContext'
import { CaliWordmark } from './CaliWordmark'
import { getAdminOverview, getAdminSystemSettings, getAuditHistory, listAdminReports, resolveAdminReport, searchAdminCommunity, searchAdminUsers, setCommunityVisibility, setPersonalLogin, setUserSuspension } from '../lib/admin'
import type { AdminOverview, AdminReport, AdminUser, AuditRow, CommunitySearch, SystemSettings } from '../lib/admin'
import './admin.css'

type Section = 'overview' | 'moderation' | 'users' | 'system'
const sections: { key: Section; label: string }[] = [{ key: 'overview', label: 'Overview' }, { key: 'moderation', label: 'Moderation' }, { key: 'users', label: 'Users' }, { key: 'system', label: 'System' }]
const message = (cause: unknown) => cause instanceof Error ? cause.message : 'The action could not be completed.'
function askReason(prompt: string) { const reason = window.prompt(prompt)?.trim() ?? ''; return reason.length >= 3 ? reason : null }

function Metric({ label, value }: { label: string; value: number | string }) { return <article className="admin-metric"><span>{label}</span><strong>{value}</strong></article> }

function Overview() {
  const [data, setData] = useState<AdminOverview | null>(null); const [audit, setAudit] = useState<AuditRow[]>([]); const [error, setError] = useState('')
  useEffect(() => { void Promise.all([getAdminOverview(), getAuditHistory()]).then(([overview, rows]) => { setData(overview); setAudit(rows.slice(0, 8)) }).catch(cause => setError(message(cause))) }, [])
  if (error) return <p className="admin-error" role="alert">{error}</p>; if (!data) return <p className="admin-loading">Loading overview…</p>
  return <><header className="admin-page-head"><p>ADMINISTRATION</p><h1>Overview</h1><span>Current Cali operations at a glance.</span></header><div className="admin-metrics"><Metric label="Total users" value={data.totalUsers}/><Metric label="Active" value={data.activeUsers}/><Metric label="Suspended" value={data.suspendedUsers}/><Metric label="Institutional" value={data.institutionalUsers}/><Metric label="Personal" value={data.personalUsers}/><Metric label="Shared reviewers" value={data.sharedReviewers}/><Metric label="Open reports" value={data.openReports}/><Metric label="Login mode" value={data.allowPersonalGoogleLogin ? 'All Google' : 'RTU only'}/></div><AuditList rows={audit}/></>
}

function Users() {
  const [users,setUsers]=useState<AdminUser[]>([]),[query,setQuery]=useState(''),[status,setStatus]=useState('all'),[account,setAccount]=useState('all'),[page,setPage]=useState(1),[total,setTotal]=useState(0),[error,setError]=useState(''),[loading,setLoading]=useState(true)
  const load=useCallback(async()=>{setLoading(true);setError('');try{const data=await searchAdminUsers(query,status,account,page);setUsers(data.items);setTotal(data.total)}catch(cause){setError(message(cause))}finally{setLoading(false)}},[query,status,account,page]); useEffect(()=>{void load()},[load])
  async function change(user:AdminUser,suspended:boolean){const reason=askReason(suspended?`Why are you suspending @${user.username}?`:`Why are you restoring @${user.username}?`);if(!reason||!window.confirm(`${suspended?'Suspend':'Restore'} @${user.username}?`))return;try{await setUserSuspension(user.userId,suspended,reason);await load()}catch(cause){setError(message(cause))}}
  return <><header className="admin-page-head"><p>ACCOUNT CONTROL</p><h1>Users</h1><span>Search accounts and manage non-destructive suspensions.</span></header><div className="admin-filters"><input aria-label="Search users" placeholder="Username, name, or email" value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}}/><select aria-label="Status" value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="all">All statuses</option><option value="active">Active</option><option value="suspended">Suspended</option><option value="admin">Administrators</option></select><select aria-label="Account type" value={account} onChange={e=>{setAccount(e.target.value);setPage(1)}}><option value="all">All accounts</option><option value="institutional">Institutional</option><option value="personal">Personal</option></select></div>{error&&<p className="admin-error">{error}</p>}{loading?<p className="admin-loading">Loading users…</p>:users.length===0?<p className="admin-empty">No users match these filters.</p>:<div className="admin-list">{users.map(user=><article key={user.userId} className="admin-row"><div><strong>@{user.username}</strong><span>{user.fullName||'No Google name'} · {user.email}</span><small>{user.program} · Year {user.yearLevel} · {user.accountType}{user.isAdmin?' · Administrator':''}</small></div><div><span className={`admin-badge ${user.suspendedAt?'is-danger':'is-ok'}`}>{user.suspendedAt?'Suspended':'Active'}</span>{!user.isAdmin&&<button onClick={()=>void change(user,!user.suspendedAt)}>{user.suspendedAt?'Restore':'Suspend'}</button>}</div></article>)}</div>}<div className="admin-pagination"><button disabled={page===1} onClick={()=>setPage(value=>value-1)}>Previous</button><span>Page {page} · {total} users</span><button disabled={page*25>=total} onClick={()=>setPage(value=>value+1)}>Next</button></div></>
}

function Moderation() {
  const [reports,setReports]=useState<AdminReport[]>([]),[content,setContent]=useState<CommunitySearch>({reviewers:[],profiles:[]}),[query,setQuery]=useState(''),[error,setError]=useState('')
  const load=useCallback(async()=>{try{const [r,c]=await Promise.all([listAdminReports(),searchAdminCommunity(query)]);setReports(r);setContent(c);setError('')}catch(cause){setError(message(cause))}},[query]);useEffect(()=>{void load()},[load])
  async function resolve(report:AdminReport,action:'dismiss'|'hide'){const reason=askReason(`Reason for ${action==='hide'?'hiding this content':'dismissing this report'}:`);if(!reason||!window.confirm(`${action==='hide'?'Hide the reported content':'Dismiss this report'}?`))return;try{await resolveAdminReport(report.id,action,reason);await load()}catch(cause){setError(message(cause))}}
  async function visibility(type:'reviewer'|'profile',id:string,hidden:boolean,label:string){const reason=askReason(`Reason for ${hidden?'hiding':'restoring'} ${label}:`);if(!reason||!window.confirm(`${hidden?'Hide':'Restore'} ${label}?`))return;try{await setCommunityVisibility(type,id,hidden,reason);await load()}catch(cause){setError(message(cause))}}
  return <><header className="admin-page-head"><p>COMMUNITY SAFETY</p><h1>Moderation</h1><span>Resolve reports and proactively review shared content.</span></header>{error&&<p className="admin-error">{error}</p>}<section className="admin-section"><h2>Open reports</h2>{reports.length===0?<p className="admin-empty">No open reports.</p>:<div className="admin-list">{reports.map(r=><article className="admin-row" key={r.id}><div><strong>{r.targetLabel||'Unavailable target'}</strong><span>{r.targetType} · Reported by @{r.reporter}</span><small>{r.reason}{r.details?` — ${r.details}`:''}</small></div><div><button onClick={()=>void resolve(r,'dismiss')}>Dismiss</button><button className="is-danger" onClick={()=>void resolve(r,'hide')}>Hide</button></div></article>)}</div>}</section><section className="admin-section"><div className="admin-section-head"><h2>Community content</h2><input placeholder="Search reviewers or profiles" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="admin-list">{content.reviewers.map(item=><article className="admin-row" key={item.id}><div><strong>{item.title}</strong><span>Reviewer by @{item.username} · {item.visibility}</span></div><button onClick={()=>void visibility('reviewer',item.id,!item.hidden,item.title)}>{item.hidden?'Restore':'Hide'}</button></article>)}{content.profiles.map(item=><article className="admin-row" key={item.userId}><div><strong>@{item.username}</strong><span>Public profile{item.suspended?' · Suspended creator':''}</span></div><button onClick={()=>void visibility('profile',item.userId,!item.hidden,`@${item.username}`)}>{item.hidden?'Restore':'Hide'}</button></article>)}</div></section></>
}

function AuditList({rows}:{rows:AuditRow[]}){return <section className="admin-section"><h2>Recent admin activity</h2>{rows.length===0?<p className="admin-empty">No administrative actions yet.</p>:<div className="admin-audit">{rows.map(row=><article key={row.id}><strong>{row.action.replaceAll('.',' ')}</strong><span>by @{row.actor}</span><time dateTime={row.createdAt}>{new Date(row.createdAt).toLocaleString()}</time></article>)}</div>}</section>}
function System() {
  const [settings,setSettings]=useState<SystemSettings|null>(null),[audit,setAudit]=useState<AuditRow[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false)
  const load=useCallback(async()=>{try{const [s,a]=await Promise.all([getAdminSystemSettings(),getAuditHistory()]);setSettings(s);setAudit(a)}catch(cause){setError(message(cause))}},[]);useEffect(()=>{void load()},[load])
  async function toggle(){if(!settings)return;const next=!settings.allowPersonalGoogleLogin;if(!window.confirm(next?'Allow any verified Google account to sign up and use Cali?':'Disable personal Google access now? Existing personal users will be blocked, but their data will remain intact.'))return;setBusy(true);try{setSettings(await setPersonalLogin(next));setAudit(await getAuditHistory())}catch(cause){setError(message(cause))}finally{setBusy(false)}}
  return <><header className="admin-page-head"><p>ACCESS POLICY</p><h1>System</h1><span>Control who may use Cali and inspect every admin mutation.</span></header>{error&&<p className="admin-error">{error}</p>}{settings&&<section className="admin-policy"><div><h2>Allow personal Google accounts</h2><p>{settings.allowPersonalGoogleLogin?'Any verified Google account can use Cali.':'Only verified @rtu.edu.ph accounts and existing administrators can use Cali.'}</p><small>Last updated {new Date(settings.updatedAt).toLocaleString()}{settings.updatedBy?` by @${settings.updatedBy}`:''}</small></div><button className={`admin-switch ${settings.allowPersonalGoogleLogin?'is-on':''}`} role="switch" aria-checked={settings.allowPersonalGoogleLogin} disabled={busy} onClick={()=>void toggle()}><span/></button></section>}<AuditList rows={audit}/></>
}

export function AdminPage(){const {state}=useAuth();const {section}=useParams();if(state.status==='loading')return <main className="admin-loading-screen">Opening administration…</main>;if(state.status==='signedOut')return <Navigate to="/login" replace/>;if(state.status==='needsOnboarding')return <Navigate to="/onboarding" replace/>;if(state.status==='ineligible')return <Navigate to="/access-denied" replace/>;if(state.status==='error')return <Navigate to="/" replace/>;if(!state.isAdmin)return <Navigate to="/dashboard" replace/>;const active=(sections.some(item=>item.key===section)?section:'overview') as Section;return <main className="admin-shell"><aside className="admin-sidebar"><CaliWordmark/><div><p>ADMIN DASHBOARD</p><strong>@{state.student.username}</strong></div><nav>{sections.map(item=><NavLink key={item.key} to={item.key==='overview'?'/admin':`/admin/${item.key}`} end={item.key==='overview'}>{item.label}</NavLink>)}</nav><div className="admin-sidebar-bottom"><Link to="/dashboard">Open Cali workspace</Link></div></aside><div className="admin-content">{active==='overview'?<Overview/>:active==='users'?<Users/>:active==='moderation'?<Moderation/>:<System/>}</div></main>}
